AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam Template for Leave Management project

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  RetentionInDays:
    Type: Number
    Description: No of days the logs should present in cloudwatch
    Default: 7

Resources:
  # LAMBDA FUNCTIONS
  # Auth lambda function
  AuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/Auth
      Handler: app.lambdaHandler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          secret: "somesecret"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval lambda function
  LeaveApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApproval
      Handler: app.lambdaHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval validator lambda function
  LeaveApprovalValidatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApprovalValidator
      Handler: app.lambdaHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Api Gateway http api
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: |
          {
            "requestId":"$context.requestId",
            "ip":"$context.identity.sourceIp",
            "requestTime":"$context.requestTime",
            "httpMethod":"$context.httpMethod",
            "routeKey":"$context.routeKey",
            "status":"$context.status"
          }
      Auth:
        DefaultAuthorizer: MyLambdaAuth
        Authorizers:
          MyLambdaAuth:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthLambda.Arn
            AuthorizerPayloadFormatVersion: 2.0
            Identity:
              Header: Authorization
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: !Ref AWS::StackName
          version: "1.0"
        paths:
          /leave-approval:
            post:
              summary: "Start Leave Approval"
              security:
                - MyLambdaAuth: []
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                integrationSubtype: "StepFunctions-StartExecution"
                credentials: !GetAtt ApiGatewaySfnRole.Arn
                requestParameters:
                  StateMachineArn: !GetAtt MyStateMachine.Arn
                payloadFormatVersion: "1.0"
              responses:
                "200":
                  description: "Execution Started"

  # Step function
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-functions/leave-approval-sm.asl.json
      DefinitionSubstitutions:
        LeaveApprovalLambdaArn: !GetAtt LeaveApprovalLambda.Arn
        LeaveApprovalValidatorLambdaArn: !GetAtt LeaveApprovalValidatorLambda.Arn
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !Sub "${StepFunctionsLogGroup.Arn}:*"

  # ROLES
  # api gateway role to access step function
  ApiGatewaySfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ApiGatewaySfnPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "states:StartExecution"
                Resource: !GetAtt MyStateMachine.Arn

  # step function role to access lambda, cloudwatch
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "states.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "StepFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt LeaveApprovalLambda.Arn
                  - !GetAtt LeaveApprovalValidatorLambda.Arn

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: "*"
  
  # LOG GROUPS
  # step function log group to see logs
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/stepfunctions/leave-approval-sm
      RetentionInDays: !Ref RetentionInDays

  # api gateway log groups
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/leave-approval-api
      RetentionInDays: !Ref RetentionInDays

Outputs:
  LeaveApprovalApi:
    Description: API Gateway endpoint URL for Prod stage for getting leave approval api
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/leave-approval"
