AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam Template for Leave Management project

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  RetentionInDays:
    Type: Number
    Description: No of days the logs should present in cloudwatch
    Default: 7

Resources:
  # LAMBDA FUNCTIONS
  # Auth lambda function
  AuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/Authorizer
      Handler: app.handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SECRET: "somesecret"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Step function trigger lambda
  StepFunctionTriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/StepFunctionExecutor
      Handler: app.handler
      Role: !GetAtt StepFunctionTriggerLambdaRole.Arn
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt MyStateMachine.Arn
      Events:
        StepFunctionTriggerApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /leave-approval
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval lambda function
  LeaveApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApproval
      Handler: app.handler
      Policies: 
       - AWSLambdaBasicExecutionRole
       - DynamoDBCrudPolicy:
            TableName: !Ref TokenTable
      Environment:
        Variables:
          TOKEN_TABLE: !Ref TokenTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval validator lambda function
  LeaveApprovalValidatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApprovalValidator
      Handler: app.handler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # DB
  # my dynamo db
  TokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Token
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH

  # Api Gateway http api
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaAuth
        Authorizers:
          MyLambdaAuth:
            FunctionArn: !GetAtt AuthLambda.Arn
            Identity:
              ReauthorizeEvery: 0

  # Step function
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-functions/leave-approval-sm.asl.json
      DefinitionSubstitutions:
        LeaveApprovalLambdaArn: !GetAtt LeaveApprovalLambda.Arn
        LeaveApprovalValidatorLambdaArn: !GetAtt LeaveApprovalValidatorLambda.Arn
      Role: !GetAtt StepFunctionsExecutionRole.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn

  # ROLES
  # step function trigger lambda role to access step function
  StepFunctionTriggerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: "StepFunctionInvokePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !GetAtt MyStateMachine.Arn

  # step function role to access lambda, cloudwatch
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "states.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "StepFunctionPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # lambda policy
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt LeaveApprovalLambda.Arn
                  - !GetAtt LeaveApprovalValidatorLambda.Arn
              # cloudwatch policy
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: "*"

  # LOG GROUPS
  # step function log group to see logs
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/stepfunctions/leave-approval-sm
      RetentionInDays: !Ref RetentionInDays

  # api gateway log groups
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/leave-approval-api
      RetentionInDays: !Ref RetentionInDays

Outputs:
  LeaveApprovalApi:
    Description: API Gateway endpoint URL for Prod stage for getting leave approval api
    Value: !Sub "https://${MyRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/leave-approval"
