AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam Template for Leave Management project

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs22.x
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON

Resources:
  # Leave approval lambda function
  LeaveApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApproval
      Handler: app.lambdaHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval validator lambda function
  LeaveApprovalValidatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApprovalValidator
      Handler: app.lambdaHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # my step function
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-functions/leave-approval-sm.asl.json
      DefinitionSubstitutions:
        LeaveApprovalLambdaArn: !GetAtt LeaveApprovalLambda.Arn
        LeaveApprovalValidatorLambdaArn: !GetAtt LeaveApprovalValidatorLambda.Arn
      Policies:
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - LambdaInvokePolicy:
            FunctionName: !Ref LeaveApprovalLambda
        - LambdaInvokePolicy:
            FunctionName: !Ref LeaveApprovalValidatorLambda
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StepFunctionsLogGroup.Arn

  # Auth lambda function
  AuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/Auth
      Handler: app.lambdaHandler
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          secret: "somesecret"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Api Gateway http api
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      AccessLogSettings:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: |
          {
            "requestId":"$context.requestId",
            "ip":"$context.identity.sourceIp",
            "requestTime":"$context.requestTime",
            "httpMethod":"$context.httpMethod",
            "routeKey":"$context.routeKey",
            "status":"$context.status"
          }
      Auth:
        DefaultAuthorizer: MyLambdaAuth
        Authorizers:
          MyLambdaAuth:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthLambda.Arn
            AuthorizerPayloadFormatVersion: 2.0
            Identity:
              Header: Authorization
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: !Ref AWS::StackName
          version: "1.0"
        paths:
          /leave-approval:
            post:
              summary: "Start Leave Approval"
              security:
                - MyLambdaAuth: []
              x-amazon-apigateway-integration:
                type: "aws_proxy"
                integrationSubtype: "StepFunctions-StartExecution"
                credentials: !GetAtt ApiGatewaySfnRole.Arn
                requestParameters:
                  StateMachineArn: !Ref MyStateMachine
                payloadFormatVersion: "1.0"
              responses:
                "200":
                  description: "Execution Started"

  ApiGatewaySfnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "ApiGatewaySfnPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "states:StartExecution"
                Resource: !Ref MyStateMachine

  # log groups
  # step function log group to see logs
  StepFunctionsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/stepfunctions/${MyStateMachine}
      RetentionInDays: 14

  # api gateway log groups
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${MyApi}
      RetentionInDays: 14

Outputs:
  LeaveApprovalApi:
    Description: API Gateway endpoint URL for Prod stage for getting leave approval api
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/leave-approval"
