AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sam Template for Leave Management project

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON

Parameters:
  RetentionInDays:
    Type: Number
    Description: No of days the logs should present in cloudwatch
    Default: 7

Resources:
  # LAMBDA FUNCTIONS
  # Auth lambda function
  AuthLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/Authorizer
      Handler: app.handler
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SECRET: "somesecret"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Step function trigger lambda
  StepFunctionTriggerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/StepFunctionExecutor
      Handler: app.handler
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - states:StartExecution
            Resource: !GetAtt MyStateMachine.Arn
      Environment:
        Variables:
          STATE_MACHINE_ARN: !GetAtt MyStateMachine.Arn
      Events:
        StepFunctionTriggerApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /leave-approval
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval lambda function
  LeaveApprovalLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApproval
      Handler: app.handler
      Timeout: 7
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TokenTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:sendEmail
                - ses:SendRawEmail
              Resource: "*"
      Environment:
        Variables:
          TOKEN_TABLE: !Ref TokenTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Step function resume lambda
  StepFunctionResumeLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/StepFunctionResumer
      Handler: app.handler
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TokenTable
        - Statement:
            Effect: Allow
            Action:
              - states:StartExecution
            Resource: !GetAtt MyStateMachine.Arn
        - Statement:
            Effect: Allow
            Action:
              - states:SendTaskSuccess
              - states:SendTaskFailure
            Resource: "*"
      Events:
        StepFunctionTriggerApi:
          Type: Api
          Properties:
            RestApiId: !Ref MyRestApi
            Path: /leave-response
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # Leave approval validator lambda function
  LeaveApprovalValidatorLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/LeaveApprovalValidator
      Handler: app.handler
      Timeout: 5
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  # DB
  # my dynamo db
  TokenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Token
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: requestId
          AttributeType: S
      KeySchema:
        - AttributeName: requestId
          KeyType: HASH

  # Api Gateway http api
  MyRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaAuth
        Authorizers:
          MyLambdaAuth:
            FunctionArn: !GetAtt AuthLambda.Arn
            Identity:
              ReauthorizeEvery: 0

  # Step function
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: step-functions/leave-approval-sm.asl.json
      DefinitionSubstitutions:
        LeaveApprovalLambdaArn: !GetAtt LeaveApprovalLambda.Arn
        LeaveApprovalValidatorLambdaArn: !GetAtt LeaveApprovalValidatorLambda.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref LeaveApprovalLambda
        - LambdaInvokePolicy:
            FunctionName: !Ref LeaveApprovalValidatorLambda

Outputs:
  LeaveApprovalApi:
    Description: API Gateway endpoint URL for Prod stage for getting leave approval api
    Value: !Sub "https://${MyRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/leave-approval"
